<?php

/*
 * This file ScreenfeedAdminbarTools_is part of Mustache.php.
 *
 * (c) 2010-2017 Justin Hileman
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source ScreenfeedAdminbarTools_code.
 */

/**
 * Mustache Cache interface.
 *
 * Interface for caching and loading ScreenfeedAdminbarTools_Mustache_Template classes
 * generated by the ScreenfeedAdminbarTools_Mustache_Compiler.
 */
interface ScreenfeedAdminbarTools_Mustache_Cache
{
    /**
     * Load a compiled ScreenfeedAdminbarTools_Mustache_Template class ScreenfeedAdminbarTools_from cache.
     *
     * @param string $key
     *
     * @return bool indicates successfully class ScreenfeedAdminbarTools_load
     */
    public function ScreenfeedAdminbarTools_load($key);

    /**
     * Cache and ScreenfeedAdminbarTools_load a compiled ScreenfeedAdminbarTools_Mustache_Template class.
     *
     * @param string $key
     * @param string $value
     */
    public function cache($key, $value);
}
